[2024-03-15T21:17:28.290+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: simple_dag.simple_task manual__2024-03-15T20:31:00.971476+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
